apiVersion: v1
kind: Pod
metadata:
  name: nginx-master
spec:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: nextg-00.ece.ncsu.edu
  containers:
  - name: nginx
    image: nginx

